# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grader_core', '0005_auto_20151205_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Scored points')),
                ('std_out', models.TextField()),
                ('std_err', models.TextField()),
                ('diff', models.TextField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader_core.Scenario')),
            ],
        ),
    ]
