# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_checker', '0003_result_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='diff',
            new_name='diff_stdout',
        ),
        migrations.AddField(
            model_name='result',
            name='diff_stderr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
