# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0009_auto_20160503_1411'),
        ('grader_checker', '0004_auto_20151205_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='Check date')),
                ('points', models.IntegerField(default=0, verbose_name='Scored points')),
                ('user', models.CharField(max_length=128, verbose_name='User')),
                ('std_out', models.TextField()),
                ('std_err', models.TextField()),
                ('diff_stdout', models.TextField()),
                ('diff_stderr', models.TextField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader_core.Scenario')),
            ],
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['user']},
        ),
    ]
