# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Exam')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
                ('date_start', models.DateTimeField(verbose_name='Starting date & time')),
                ('date_end', models.DateTimeField(verbose_name='End date & time')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_type', models.CharField(choices=[('hg', 'Mercurial (hg)'), ('svn', 'Subversion (SVN)'), ('git', 'GIT')], max_length=24, verbose_name='Type')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('diff', 'Diff')], max_length=16, verbose_name='Type')),
                ('pattern_stdout', models.TextField(blank=True, null=True, verbose_name='Expected standard output')),
                ('pattern_stderr', models.TextField(blank=True, null=True, verbose_name='Expected standard error output')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader_core.Exam')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader_core.Task'),
        ),
        migrations.AddField(
            model_name='exam',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader_core.Repository'),
        ),
    ]
