# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Repository', 'verbose_name_plural': 'Repositories'},
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_id',
            field=models.CharField(default='x', max_length=128, unique=True, verbose_name='Repository id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Exam short name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('hg', 'Mercurial (hg)'), ('git', 'GIT'), ('svn', 'Subversion (SVN)')], max_length=24, verbose_name='Type'),
        ),
    ]
