# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0002_auto_20151205_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='path',
            field=models.CharField(default='x', max_length=256, verbose_name='Source path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='x', max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Exam short name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('git', 'GIT'), ('svn', 'Subversion (SVN)'), ('hg', 'Mercurial (hg)')], max_length=24, verbose_name='Type'),
        ),
    ]
