# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0003_auto_20151205_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points for this scenario'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('svn', 'Subversion (SVN)'), ('git', 'GIT'), ('hg', 'Mercurial (hg)')], max_length=24, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_type',
            field=models.CharField(choices=[('diff', 'Diff')], help_text='Available scenario types:<br>Diff - a standard output comparison. This test looks at either stdout or stderr (or both). Can score either 0% or 100% available points.', max_length=16, verbose_name='Type'),
        ),
    ]
