# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0004_auto_20151205_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('git', 'GIT'), ('svn', 'Subversion (SVN)'), ('hg', 'Mercurial (hg)')], max_length=24, verbose_name='Type'),
        ),
    ]
