# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader_environments', '0003_auto_20160103_1432'),
        ('grader_core', '0005_auto_20151205_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='runtime_env_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grader_environments.RuntimeEnvironmentGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('hg', 'Mercurial (hg)'), ('svn', 'Subversion (SVN)'), ('git', 'GIT')], max_length=24, verbose_name='Type'),
        ),
    ]
