# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0006_auto_20160103_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('git', 'GIT'), ('hg', 'Mercurial (hg)'), ('svn', 'Subversion (SVN)')], max_length=24, verbose_name='Type'),
        ),
    ]
