# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_core', '0008_auto_20160123_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('hg', 'Mercurial (hg)'), ('svn', 'Subversion (SVN)'), ('git', 'GIT')], max_length=24, verbose_name='Type'),
        ),
    ]
