# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('host', models.CharField(max_length=512, verbose_name='Host')),
                ('username', models.CharField(max_length=256, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=512, null=True, verbose_name='Password')),
            ],
        ),
    ]
